# Generated by Django 4.2.1 on 2023-05-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=100)),
                ('salary', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('F', 'F'), ('M', 'M')], max_length=1, null=True)),
                ('jobtype', models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Intern', 'Intern'), ('Fullstack', 'Fullstack')], max_length=50)),
            ],
        ),
    ]
